"""
Utilities for managing beets configuration.
"""

import os
import yaml
from pathlib import Path
from typing import Optional


class BeetsConfigError(Exception):
    """Exception raised for beets config-related errors."""
    pass


def get_default_config_path() -> Path:
    """
    Get the default beets config path.
    
    Returns:
        Path to beets config file
    """
    return Path.home() / '.config' / 'beets' / 'config.yaml'


def create_beets_config(
    config_path: Optional[Path] = None,
    mountpoint: str = '/Volumes/XTRAINERZ',
    bitrate: str = '96k',
    max_bitrate: int = 128
) -> Path:
    """
    Create a beets configuration file optimized for Shokz XTRAINERZ.
    
    Args:
        config_path: Path where config should be written (default: ~/.config/beets/config.yaml)
        mountpoint: Mount point of the USB device
        bitrate: Target bitrate for transcoding (e.g., '96k')
        max_bitrate: Only transcode files above this bitrate (kbps)
        
    Returns:
        Path to the created config file
        
    Raises:
        BeetsConfigError: If config cannot be written
    """
    if config_path is None:
        config_path = get_default_config_path()
    
    # Ensure parent directory exists
    config_path.parent.mkdir(parents=True, exist_ok=True)
    
    # Build config structure
    config = {
        'directory': mountpoint,
        'library': str(Path.home() / '.config' / 'beets' / 'shokz_music.db'),
        
        'import': {
            'move': True,
            'copy': False,
            'write': True,
            'autotag': True,
            'incremental': True,
            'resume': 'ask',
            'quiet_fallback': 'skip',
        },
        
        'paths': {
            'default': '$albumartist - $album/%if{$track,$track - }$title',
            'singleton': '$artist/$title',
            'comp': 'Compilations/$album/%if{$track,$track - }$title',
        },
        
        'plugins': ['scrub', 'convert'],
        
        'scrub': {
            'auto': True,
        },
        
        'convert': {
            'auto': False,  # We'll call it explicitly when needed
            'copy_album_art': True,
            'max_bitrate': max_bitrate,
            'dest': mountpoint,
            'format': 'aac',
            'opts': f'-b:a {bitrate}',
        },
    }
    
    try:
        with open(config_path, 'w') as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)
        
        return config_path
    
    except Exception as e:
        raise BeetsConfigError(f"Failed to write config to {config_path}: {e}")


def load_beets_config(config_path: Optional[Path] = None) -> dict:
    """
    Load an existing beets config file.
    
    Args:
        config_path: Path to config file (default: ~/.config/beets/config.yaml)
        
    Returns:
        Config dictionary
        
    Raises:
        BeetsConfigError: If config cannot be loaded
    """
    if config_path is None:
        config_path = get_default_config_path()
    
    if not config_path.exists():
        raise BeetsConfigError(f"Config file not found: {config_path}")
    
    try:
        with open(config_path, 'r') as f:
            config = yaml.safe_load(f)
        return config or {}
    except Exception as e:
        raise BeetsConfigError(f"Failed to load config from {config_path}: {e}")


def verify_beets_config(config_path: Optional[Path] = None) -> bool:
    """
    Check if a valid beets config exists.
    
    Args:
        config_path: Path to config file
        
    Returns:
        True if config exists and is valid, False otherwise
    """
    if config_path is None:
        config_path = get_default_config_path()
    
    if not config_path.exists():
        return False
    
    try:
        config = load_beets_config(config_path)
        # Basic validation: check for required keys
        return 'directory' in config and 'library' in config
    except BeetsConfigError:
        return False


def get_config_template() -> str:
    """
    Get the beets config template as a string.
    
    Returns:
        YAML config template
    """
    return """# Beets configuration for Shokz XTRAINERZ
# Generated by shokz-sync

directory: /Volumes/XTRAINERZ
library: ~/.config/beets/shokz_music.db

import:
  move: yes
  copy: no
  write: yes
  autotag: yes
  incremental: yes
  resume: ask
  quiet_fallback: skip

paths:
  default: $albumartist - $album/%if{$track,$track - }$title
  singleton: $artist/$title
  comp: Compilations/$album/%if{$track,$track - }$title

plugins:
  - scrub
  - convert

scrub:
  auto: yes

convert:
  auto: no
  copy_album_art: yes
  max_bitrate: 128
  dest: /Volumes/XTRAINERZ
  format: aac
  opts: '-b:a 96k'
"""

